[package]
name = "femto"
version = "0.0.3"
authors = ["Dariusz Depta <wisbery@users.noreply.github.com>"]
description = "Future project"
documentation = "https://docs.rs/femto"
repository = "https://github.com/wisbery/femto.git"
license = "MIT OR Apache-2.0"
edition = "2021"
