version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  doc:
    desc: Generates the documentation
    cmds:
      - cmd: cargo doc --no-deps

  doc-open:
    desc: Generates the documentation and opens it in the browser
    cmds:
      - cmd: cargo doc --no-deps --open

  test:
    desc: Tests the library in debug mode
    cmds:
      - cmd: cargo test

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo clippy --all-targets

  fmt:
    desc: Runs the code formatter
    cmds:
      - cmd: cargo +nightly fmt
